[package]
name = "gmux"
version = "0.1.0"
edition = "2024"

[dependencies]
fontconfig = "0.9.0"
ini = "1.3.0"
lazy_static = "1.5.0"
libc = "0.2.175"
log = "0.4"
simplelog = "0.12"
toml = "0.5.9"
x11 = "2.21.0"
fuzzy-matcher = "0.3.7"
chrono = "0.4"

[profile.dev]
opt-level = 1
